CREATE TABLE FREEBOARD (
    FREEBOARD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    FREEBOARD_TITLE VARCHAR(255) DEFAULT NULL,
    FREEBOARD_CONTENT LONGTEXT DEFAULT NULL,
    FREEBOARD_PLAIN_TEXT LONGTEXT DEFAULT NULL,
    FREEBOARD_CLICK BIGINT DEFAULT 0,
    FREEBOARD_IMAGE VARCHAR(255) DEFAULT NULL,
    FREEBOARD_REPRESENT_IMAGE VARCHAR(255) DEFAULT NULL,
    FREEBOARD_CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FREEBOARD_DELETED_YN CHAR(1) NOT NULL DEFAULT 'N',
    INDEX IDX_FREEBOARD_USER (USER_ID),
    INDEX IDX_FREEBOARD_CREATED (FREEBOARD_CREATED_AT DESC),
    CONSTRAINT FK_FREEBOARD_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CODEBOARD 테이블 생성
CREATE TABLE CODEBOARD (
    CODEBOARD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ANALYSIS_ID VARCHAR(255) NOT NULL,
    CODEBOARD_TITLE VARCHAR(500) NOT NULL,
    CODEBOARD_BLOCKS TEXT NOT NULL,
    CODEBOARD_PLAIN_TEXT TEXT,
    CODEBOARD_CLICK BIGINT DEFAULT 0,
    CODEBOARD_CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CODEBOARD_DELETED_YN VARCHAR(1) DEFAULT 'N',

    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_ANALYSIS_ID (ANALYSIS_ID),
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_CREATED_AT (CODEBOARD_CREATED_AT),
    INDEX IDX_DELETED_YN (CODEBOARD_DELETED_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE TAG (
    TAG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TAG_NAME VARCHAR(50) NOT NULL UNIQUE,
    INDEX IDX_TAG_NAME (TAG_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE FREEBOARD_TAG (
    FREEBOARD_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL,
    TAG_DISPLAY_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (FREEBOARD_ID, TAG_ID),
    INDEX IDX_FREEBOARD_TAG_TAG (TAG_ID),
    CONSTRAINT FK_FREEBOARD_TAG_FREEBOARD
        FOREIGN KEY (FREEBOARD_ID) REFERENCES FREEBOARD(FREEBOARD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FREEBOARD_TAG_TAG
        FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CODEBOARD_TAG 매핑 테이블 생성
CREATE TABLE CODEBOARD_TAG (
    CODEBOARD_TAG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODEBOARD_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL,
    TAG_DISPLAY_NAME VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (CODEBOARD_ID) REFERENCES CODEBOARD(CODEBOARD_ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_CODEBOARD_TAG (CODEBOARD_ID, TAG_ID),
    INDEX IDX_TAG_ID (TAG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `COMMENT` (
    COMMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOARD_ID BIGINT NOT NULL,
    BOARD_TYPE VARCHAR(20) NOT NULL,
    PARENT_COMMENT_ID BIGINT NULL,
    USER_ID BIGINT NOT NULL,
    CONTENT TEXT NOT NULL,
    LIKE_COUNT INT DEFAULT 0,
    IS_DELETED TINYINT(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_COMMENT_PARENT (PARENT_COMMENT_ID),
    INDEX IDX_COMMENT_USER (USER_ID),
    INDEX IDX_COMMENT_BOARD (BOARD_TYPE, BOARD_ID, CREATED_AT),
    CONSTRAINT FK_COMMENT_PARENT
        FOREIGN KEY (PARENT_COMMENT_ID) REFERENCES COMMENT(COMMENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `LIKE` (
    LIKE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    REFERENCE_TYPE VARCHAR(20) NOT NULL,
    REFERENCE_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_LIKE_REFERENCE (REFERENCE_TYPE, REFERENCE_ID),
    INDEX IDX_LIKE_USER (USER_ID, CREATED_AT),
    UNIQUE KEY UK_LIKE_USER_REFERENCE (USER_ID, REFERENCE_TYPE, REFERENCE_ID),
    CONSTRAINT FK_LIKE_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE NOTIFICATION (
    NOTIFICATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RECIPIENT_ID BIGINT NOT NULL,
    SENDER_ID BIGINT NULL,
    NOTIFICATION_TYPE VARCHAR(50) NOT NULL,
    REFERENCE_TYPE VARCHAR(20) NOT NULL,
    REFERENCE_ID BIGINT NOT NULL,
    MESSAGE TEXT,
    IS_READ TINYINT(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_NOTIFICATION_RECIPIENT_READ (RECIPIENT_ID, IS_READ, CREATED_AT),
    INDEX IDX_NOTIFICATION_REFERENCE (REFERENCE_TYPE, REFERENCE_ID),
    CONSTRAINT FK_NOTIFICATION_RECIPIENT
        FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTIFICATION_SENDER
        FOREIGN KEY (SENDER_ID) REFERENCES USERS(USER_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;